# Generated by Django 6.1 on 2026-08-11 13:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=30, null=True)),
                ('discount_type', models.CharField(choices=[('regular', 'Regular'), ('student', 'Student'), ('senior', 'Senior'), ('pwd', 'PWD')], default='regular', max_length=20)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(max_length=255)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('route_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('cashier', 'Cashier')], default='cashier', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DailyRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_name', models.CharField(max_length=255)),
                ('dispatcher_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('driver_name', models.CharField(max_length=255)),
                ('terminal_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ps_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('water_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('dispatcher_collection_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ftb', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('savings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('trust_fund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_remittances', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_remittances', to='core.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='ManifestTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifest_trips', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifest_trips', to='core.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('lost', 'Lost'), ('deactivated', 'Deactivated')], default='active', max_length=20)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='core.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('topup', 'Top-up'), ('fare', 'Fare')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.card')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.route')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.trip')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='core.vehicle'),
        ),
        migrations.CreateModel(
            name='DispatchRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('departure_time', models.TimeField()),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rounds', to='core.dailyremittance')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('remittance', 'round_number'), name='unique_round_number_per_remittance')],
            },
        ),
        migrations.CreateModel(
            name='FareManifestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_count', models.PositiveIntegerField()),
                ('discount_count', models.PositiveIntegerField(default=0)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(choices=[('rfid', 'RFID'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('manifest_trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='core.manifesttrip')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifest_entries', to='core.route')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_count__lte', models.F('passenger_count'))), name='discount_count_lte_passenger_count'), models.UniqueConstraint(fields=('manifest_trip', 'route'), name='unique_route_per_manifest_trip')],
            },
        ),
    ]
