# Generated by Django 6.1 on 2026-08-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_manifesttrip_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='discount_fare',
        ),
        migrations.AddField(
            model_name='manifesttrip',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manifesttrip',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route',
            name='discount_exempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='manifesttrip',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
