# Generated by Django 6.1 on 2026-08-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_route_discount_fare_manifesttrip_finalized_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Route',
            new_name='Destination',
        ),
        migrations.RemoveConstraint(
            model_name='faremanifestentry',
            name='unique_route_per_manifest_trip',
        ),
        migrations.RenameField(
            model_name='faremanifestentry',
            old_name='route',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='route',
            new_name='destination',
        ),
        migrations.AddConstraint(
            model_name='faremanifestentry',
            constraint=models.UniqueConstraint(fields=('manifest_trip', 'destination'), name='unique_destination_per_manifest_trip'),
        ),
    ]
