# Generated by Django 6.1 on 2026-08-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_route_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='capacity_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
