# Generated by Django 6.1 on 2026-08-16 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_line_vehicle_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='capacity_limit',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
