# Generated by Django 6.1 on 2026-08-16 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_destination_capacity_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='passenger_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
