# Generated by Django 6.1 on 2026-08-16 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_vehicle_passenger_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.CharField(max_length=255)),
                ('new_value', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifest_corrections', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='core.faremanifestentry')),
                ('manifest_trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='core.manifesttrip')),
            ],
        ),
    ]
