# Generated by Django 6.1 on 2026-08-23 01:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_manifestcorrection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=12)),
                ('ps_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('water_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('dispatcher_collection_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ftb', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('savings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('trust_fund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_light_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='core.driver'),
        ),
    ]
