# Generated by Django 6.1 on 2026-08-26 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_dispatcher_dailyremittance_dispatcher'),
    ]

    operations = [
        migrations.CreateModel(
            name='TapLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_uid', models.CharField(max_length=100)),
                ('passenger_name', models.CharField(blank=True, max_length=255)),
                ('success', models.BooleanField()),
                ('message', models.CharField(max_length=255)),
                ('fare_charged', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remaining_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tap_logs', to='core.card')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tap_logs', to='core.destination')),
            ],
        ),
    ]
