# Generated by Django 6.1 on 2026-08-28 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_currenttapselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='currenttapselection',
            name='manifest_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_tap_selections', to='core.manifesttrip'),
        ),
    ]
