# Generated by Django 6.1 on 2026-08-28 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_currenttapselection_manifest_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='taplog',
            name='fare_type',
            field=models.CharField(blank=True, choices=[('base', 'Base'), ('discount', 'Discount')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='taplog',
            name='manifest_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tap_logs', to='core.manifesttrip'),
        ),
        migrations.AddField(
            model_name='taplog',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taplog',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taplog',
            name='refunded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunded_tap_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('topup', 'Top-up'), ('fare', 'Fare'), ('refund', 'Refund')], max_length=20),
        ),
    ]
