# Generated by Django 6.1 on 2026-08-30 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_adminauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='taplog',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_tap_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taplog',
            name='source',
            field=models.CharField(choices=[('rfid', 'RFID'), ('manual', 'Manual')], default='rfid', max_length=20),
        ),
    ]
