# Generated by Django 6.1 on 2026-09-13 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_transaction_is_reversed_transaction_reversal_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchRoundLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('departure_time', models.TimeField()),
                ('action', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_round_logs', to=settings.AUTH_USER_MODEL)),
                ('remittance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='round_logs', to='core.dailyremittance')),
            ],
        ),
    ]
