# Generated by Django 6.1 on 2026-09-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_dispatchroundlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchroundlog',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
