# Generated by Django 6.1 on 2026-09-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_dispatchroundlog_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='participates_in_savings_trust_fund',
            field=models.BooleanField(default=True),
        ),
    ]
