# Generated by Django 6.1 on 2026-09-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_driver_participates_in_savings_trust_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='participates_in_savings_trust_fund',
        ),
        migrations.AddField(
            model_name='driver',
            name='participates_in_savings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='participates_in_trust_fund',
            field=models.BooleanField(default=True),
        ),
    ]
