# Generated by Django 6.1 on 2026-09-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_driver_participates_in_savings_trust_fund_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifesttrip',
            name='boarding_code_index',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
