# Generated by Django 6.1 on 2026-09-22 05:00

import django.db.models.deletion
from django.db import migrations, models


def assign_existing_destinations_to_single_line(apps, schema_editor):
    Line = apps.get_model('core', 'Line')
    Destination = apps.get_model('core', 'Destination')
    line = Line.objects.order_by('id').first()
    if line is not None:
        Destination.objects.filter(line__isnull=True).update(line=line)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_manifesttrip_boarding_code_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.line'),
        ),
        migrations.RunPython(assign_existing_destinations_to_single_line, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='destination',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.line'),
        ),
    ]
