# Generated by Django 6.1 on 2026-09-24 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_destination_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchround',
            name='departure_terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.terminal'),
        ),
        migrations.AddField(
            model_name='dispatchround',
            name='source_trip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_round', to='core.manifesttrip'),
        ),
        migrations.AddField(
            model_name='manifesttrip',
            name='departure_terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.terminal'),
        ),
        migrations.AlterField(
            model_name='dispatchroundlog',
            name='action',
            field=models.CharField(choices=[('added', 'Added'), ('removed', 'Removed'), ('auto_generated', 'Auto-generated')], max_length=20),
        ),
    ]
