# Generated by Django 6.1 on 2026-09-24 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_dispatchround_departure_terminal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchround',
            name='round_number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
