# Generated by Django 6.1 on 2026-09-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_dispatchround_round_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchround',
            name='is_excluded',
            field=models.BooleanField(default=False),
        ),
    ]
