# Generated by Django 6.1 on 2026-09-24 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_dispatchround_is_excluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifesttrip',
            name='dispatcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.dispatcher'),
        ),
    ]
