# Generated by Django 6.1 on 2026-09-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_manifesttrip_dispatcher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyremittance',
            name='dispatcher',
        ),
    ]
