# Generated by Django 6.1 on 2026-09-25 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_manifesttrip_cancelled_at_manifesttrip_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyremittance',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyremittance',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_daily_remittances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyremittance',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
