# Generated by Django 6.1 on 2026-09-25 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_dailyremittance_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='core.passenger'),
        ),
    ]
