# Generated by Django 6.1 on 2026-09-25 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_card_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taplog',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tap_logs', to='core.destination'),
        ),
    ]
