# Generated by Django 6.1 on 2026-09-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_taplog_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatcher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='line',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
