# Generated by Django 6.1 on 2026-09-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_dispatcher_is_active_line_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
