# Generated by Django 6.1 on 2026-09-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_add_driver_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='taplog',
            name='is_correction',
            field=models.BooleanField(default=False),
        ),
    ]
